apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "balloons.book.dong.io"
spec:
  group: "book.dong.io"
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                releaseTime:
                  type: "string"
                  format: "date-time"
            status:
              type: object
              properties:
                status:
                  type: "string"
      subresources:
        # status enables the status subresource.
        status: { }

  scope: "Namespaced"
  names:
    plural: "balloons"
    singular: "balloon"
    kind: "Balloon"
